services:
    app:
        image: ${APP_NAME:-symfony}-app:local
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            target: local
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
