---
name: 'Branch: main'
on:
    push:
        branches: [ 'main' ]
    workflow_dispatch:
jobs:
    code_quality:
        name: 'Code Quality'
        uses: ./.github/workflows/code-quality.yaml
    deploy_prod:
        name: 'Deploy'
        needs:
            - code_quality
        uses: ./.github/workflows/deploy-prod.yaml
        secrets: inherit
